### ISSUE TITLE
Unit test fails with -dip1000

### ISSUE THREAD

**Issue by chloekek** [pbackus/sumtype#23] opened 2019-06-12 20:41 UTC
Compiling with -dip1000 succeeds, but the following unit test fails:

https://github.com/pbackus/sumtype/blob/b6a24cb4fbd3cb6c116e49ae8ec78a65ab8055a6/src/sumtype.d#L1306-L1311

Using DMD v2.085.1:

```bash
dmd -debug -main -unittest -dip1000 sumtype.d
```

When compiling without -dip1000, the test passes.

**Comment by pbackus** [comment] 2019-06-14 18:49
Can't reproduce with dmd v2.086, but I'm running into a different dip1000 issue with the assignment `x = t` in this unit test:

https://github.com/pbackus/sumtype/blob/b6a24cb4fbd3cb6c116e49ae8ec78a65ab8055a6/src/sumtype.d#L561-L566

The error:

    Error: `@safe` function `sumtype.__unittest_L527_C7` cannot call `@system` function `sumtype.SumType!(int, Test).SumType.opAssign!().opAssign`

Manually annotating `opAssign` as `@safe` changes it to:

    Error: address of variable `rhs` assigned to `this` with longer lifetime

This seems wrong, because while the *value* of `rhs` is assigned to `this`, the *address* shouldn't be. But it's also possible I've misused `auto ref` and/or `forward` in some subtle way.

**Closed** 2019-06-21 00:49 UTC

**Comment by pbackus** [comment] 2019-06-21 00:50
Turns out the issue I encountered was related to the hidden context pointer in `t`. Changing the parameters of `opAssign` and `Storage`'s constructor to be `scope auto ref` fixes it, though I'm not entirely sure I understand why.

The failing unit test from the original report is unrelated, but has also been fixed.
