### ISSUE TITLE
SumType doesn't hold a struct that defines a copy-constructor

### ISSUE THREAD

**Issue by aminya** [pbackus/sumtype#72] opened 2021-08-22 03:05 UTC
I get this error:
```d
C:\tools\ldc2-1.27.0-beta2-windows-x64\bin\..\import\std\sumtype.d-mixin-399(399,41): Error: none of the overloads of `__ctor` are callable using a `const` object, candidates are:
****:        `MyStruct.this(Data* data)`
****:        `MyStruct.this(return ref scope Data otherData)`
C:\tools\ldc2-1.27.0-beta2-windows-x64\bin\..\import\std\sumtype.d(395,17): Error: constructor `std.sumtype.SumType!(Data, string).SumType.this` label `__returnLabel` is undefined
C:\tools\ldc2-1.27.0-beta2-windows-x64\bin\..\import\std\sumtype.d-mixin-417(417,45): Error: none of the overloads of `__ctor` are callable using a `immutable` object, candidates are:
****:        `MyStruct.this(Data* data)`
****:        `MyStruct.this(return ref scope Data otherData)`
C:\tools\ldc2-1.27.0-beta2-windows-x64\bin\..\import\std\sumtype.d(413,17): Error: constructor `std.sumtype.SumType!(Data, string).SumType.this` label `__returnLabel` is undefined
****: Error: template instance `std.sumtype.SumType!(Data, string)` error instantiating
```

The struct defines this copy constructor:
```d
struct MyStruct {
  Data* data
  this(Data* data) @nogc nothrow
  {
	this.data = data;
  }

  this(ref return scope Data otherData) @nogc nothrow
  {
	// ....
  }
  @disable this(this);
}
```

I am trying to use 
```d
SumType!(MyStruct, string)
```

**Comment by aminya** [comment] 2021-08-22 03:30
Adding the following constructor fixes the issue. However, I am not sure if that's the generic solution.
```
  this(ref return scope inout Data otherData) @nogc nothrow inout
  {
	// ....
  }
```

**Comment by pbackus** [comment] 2021-08-22 04:37
Your example does not compile as written. I attempted to fix it, resulting in this unit test:

```d
@safe unittest {
	static struct Data
	{
		Data* data;

		this(Data* data) @nogc nothrow
		{
			this.data = data;
		}

		this(ref return scope Data otherData) @nogc nothrow
		{
			// ....
		}
		@disable this(this);
	}

	SumType!(Data, string) x;
}
```

...but I cannot reproduce the error—the test above compiles successfully.

**Comment by pbackus** [comment] 2021-08-22 04:40
Also: please make sure you are using sumtype version 1.1.3 or higher. It's possible you are running into a bug that has already been fixed.

**Comment by aminya** [comment] 2021-08-22 05:28
I think I tested with the latest version, but I will have to create a minimal working example so you can diagnose the issue.

**Comment by pbackus** [comment] 2021-09-12 15:53
@aminya Any progress?

**Comment by aminya** [comment] 2021-09-13 02:46
I published the code. This is the constructor I was talking about.
https://github.com/aminya/d-tree-sitter/blob/215b537b6e855b8cb3bf41c874dab34395f0dee6/src/d_tree_sitter/tree.d#L40

It was fixed by adding this:
https://github.com/aminya/d-tree-sitter/blob/215b537b6e855b8cb3bf41c874dab34395f0dee6/src/d_tree_sitter/tree.d#L46

**Comment by pbackus** [comment] 2021-09-13 04:29
Looking back at your original comment, I think I see the problem. You are using `std.sumtype`, the Phobos module, not the `sumtype` dub package. The fix for your issue has already been release in the dub package, but will not be fixed in Phobos until the next release, version 2.098.

In the future, please submit bug reports for the Phobos module `std.sumtype` to [issues.dlang.org][1]. In this case, your issue is a duplicate of [issue 22077][2], so there is no need to resubmit.

[1]: https://issues.dlang.org/
[2]: https://issues.dlang.org/show_bug.cgi?id=22077

**Closed by pbackus** 2021-09-13 04:29 UTC

**Comment by aminya** [comment] 2021-09-13 04:57
Oh, thanks! I didn't notice that. Sorry about that.
